### ISSUE TITLE
Create testing system

### ISSUE THREAD

**Issue by DamonGreenhalgh** [uoa-compsci399-s2-2022/spatial-skills-web-app#5]
## Feature Description
This is the main test interface.

## User Story
"As a user I would like to be tested on my spatial ability"

## MVP
A test page and question component for multi-choice and text input questions.

**Comment by wukelang** [comment]
Just wrote the barbones HTML for the testing page. Going to work on CSS and polish it up a bit

Is there a way you want to write the className for each html element? I noticed you used home__[] for the homepage so I'm thinking I should keep it consistent

**Comment by DamonGreenhalgh** [comment]
I usually use the [Block Element Modifier](http://getbem.com/naming/) naming convention. But you don't need to follow it directly, as long as it remains readable it should be fine.

**Comment by wukelang** [comment]
Just to make sure, when you want the components to be functional components, should they be written as:
`const Test = () => {}`
or
`function Test() {}`
@DamonGreenhalgh

**Comment by DamonGreenhalgh** [comment]
The first approach would be good!

**Comment by wukelang** [comment]
## **Documentation**

Components require react-icons package.

### Test Component
Currently imports question images from local assets, with hard coded question properties (time, type, text).
Has questionNum, questionTime and userAnswer state variables.
- questionNum represents the current question index in the question bank.
- questionTime acts as the remaining time in seconds for the current question, which gets used for the timer.
- userAnswer is an array that gets updated at the questionNum index when the user picks / enters an answer.

The timer countdown, next question and answer submission logic is all within this component.
The component itself renders other components responsible for displaying this logic. They are separated into 3 sections; left bar (timer), content (question, question text, answers) and right bar (progress, next button).

### Timer Display
Renders the remaining time parsed from the test component (questionTime) in a minutes : seconds format. 
When the time remaining is less than 10 seconds, the text turns red.

### Next Button
Renders a button with a right arrow icon that when clicked, performs the parsed onClick function (nextQuestion()).

### Timer Progress
Renders text that displays the parsed current question number (questionNum) and the total questions in the test.

### Question
Renders the image of the question parsed from the test component.

### Answer
Has logic that determines whether to render multichoice answers / text entry answer based on the parsed question type.
It renders a form that contains the appropriate answer(s), parsing the submitAnswer() event handler to its child components.
- Multichoice Answer: radio buttons for each question image  - 1.  Background goes blue when hovered over.
- Text Entry Answer: text input element. Textbox background goes blue when selected / hovered over.

## Potential issues to work on in the future
- Multichoice answers do not deselect themselves after changing questions; they will stay on the previous option value.
- Image sizes. I've set a max size for the question / multichoice answer images, but it may not be suitable for all images.
- No animations between question changes. If possible, a fade out / fade in when we change question.
- Check if the user has selected / entered an answer when they click of the next question button.
- May not be super compatible for smaller resolutions
- Add the moving time slider made by Ethan
